import type { Study } from "./types";

export const sampleStudy: Study = {
  id: "study-onboarding",
  title: "New customer onboarding",
  goal: "Understand where small business owners lose confidence during their first week and what helps them reach their first successful outcome.",
  context: "A self-serve invoicing product is seeing strong sign-up growth, but only 38% of new accounts send an invoice in the first seven days.",
  targetUsers: "First-time customers at small service businesses, signed up within the last 30 days.",
  questions: ["What do customers expect after sign-up?", "Where do they hesitate or abandon setup?", "What creates a sense of progress?"],
  hypotheses: "Customers need an example invoice before they feel confident creating their own.",
  status: "analysed",
  updatedAt: "18 minutes ago",
  interviews: [
    { id: "i1", participant: { id: "p1", code: "P01", role: "Studio owner", segment: "New customer", accent: "coral" }, title: "Onboarding interview · P01", date: "Jul 14", source: "paste", wordCount: 2841, status: "ready", summary: "Wanted to send an invoice quickly but paused when tax and payment settings appeared before the first draft.", transcript: "Researcher: Tell me what you expected when you first signed in.\n\nP01: I thought I would make one invoice and learn the rest later. Instead, it asked me about tax and payment terms straight away. I wasn't sure what could be changed later, so I stopped.\n\nResearcher: What would have helped?\n\nP01: Show me a finished example first. Then I can understand what all these settings are building toward. I don't want to configure everything before I know what good looks like." },
    { id: "i2", participant: { id: "p2", code: "P02", role: "Consultant", segment: "Switched product", accent: "mint" }, title: "Onboarding interview · P02", date: "Jul 14", source: "txt", wordCount: 3190, status: "ready", summary: "Imported clients successfully but could not tell whether setup was complete enough to send a real invoice.", transcript: "Researcher: Where did you feel least certain?\n\nP02: There was no moment where it said, you're ready. I kept opening settings because I thought I had missed something.\n\nResearcher: What did you do next?\n\nP02: I sent myself a test invoice. That gave me confidence, but I had to invent that step. The product never suggested it." },
    { id: "i3", participant: { id: "p3", code: "P03", role: "Freelance designer", segment: "New customer", accent: "violet" }, title: "Onboarding interview · P03", date: "Jul 15", source: "docx", wordCount: 2674, status: "ready", summary: "Relied on a colleague's setup and wanted reassurance about which fields clients would actually see.", transcript: "Researcher: What was confusing about the setup?\n\nP03: I couldn't tell what the client would see versus what was just for me. A preview would have solved most of it.\n\nResearcher: Did anything help?\n\nP03: My colleague showed me hers. Once I saw the end result, the form made sense. Before that, every field felt like a decision I could get wrong." },
    { id: "i4", participant: { id: "p4", code: "P04", role: "Agency founder", segment: "New customer", accent: "blue" }, title: "Onboarding interview · P04", date: "Jul 16", source: "pdf", wordCount: 3512, status: "ready", summary: "Completed setup but postponed inviting a teammate because permissions were introduced without context.", transcript: "Researcher: How did setup feel overall?\n\nP04: The checklist was useful because I could see progress. But inviting my team felt risky—I didn't know what access they would get.\n\nResearcher: What would you change?\n\nP04: Let me finish one invoice first. Team setup matters, just not before I've proved the basic workflow to myself." },
    { id: "i5", participant: { id: "p5", code: "P05", role: "Bookkeeper", segment: "Switched product", accent: "amber" }, title: "Onboarding interview · P05", date: "Jul 16", source: "paste", wordCount: 2988, status: "ready", summary: "Moved quickly through familiar fields but wanted a safe test state before sending to a customer.", transcript: "Researcher: What were you trying to achieve in the first session?\n\nP05: Just send a test and check the layout. I knew the accounting terms, but I still didn't want my first attempt going to a real client.\n\nResearcher: How did you manage that?\n\nP05: I used my personal email as the customer. A built-in test mode would have been much cleaner." }
  ],
  themes: [
    { id: "t1", title: "Confidence comes from seeing the outcome", summary: "Participants understood configuration choices only after seeing a finished invoice or preview. The current flow asks for commitment before it provides a clear mental model.", strength: "dominant", participantCount: 4, status: "draft", tags: ["Need", "Mental model"], x: 80, y: 80, evidence: [
      { id: "e1", interviewId: "i1", participantCode: "P01", participantRole: "Studio owner", quote: "Show me a finished example first. Then I can understand what all these settings are building toward.", context: "P01 expected to create an invoice before configuring tax and payment settings. Uncertainty about whether settings could be changed caused them to stop.", segmentId: "i1-s4" },
      { id: "e2", interviewId: "i3", participantCode: "P03", participantRole: "Freelance designer", quote: "Once I saw the end result, the form made sense. Before that, every field felt like a decision I could get wrong.", context: "P03 used a colleague's completed setup as an external reference because the product did not preview the client-facing outcome.", segmentId: "i3-s4" },
      { id: "e3", interviewId: "i5", participantCode: "P05", participantRole: "Bookkeeper", quote: "I still didn't want my first attempt going to a real client.", context: "Despite domain familiarity, P05 wanted a safe way to inspect the finished result before committing.", segmentId: "i5-s2" }
    ]},
    { id: "t2", title: "There is no clear ‘ready’ moment", summary: "Customers keep checking settings because the product never confirms that the minimum setup is complete. Self-created tests become a substitute for product reassurance.", strength: "recurring", participantCount: 3, status: "draft", tags: ["Pain point", "Behaviour"], x: 470, y: 250, evidence: [
      { id: "e4", interviewId: "i2", participantCode: "P02", participantRole: "Consultant", quote: "There was no moment where it said, you're ready. I kept opening settings because I thought I had missed something.", context: "P02 had imported client data but could not identify whether the account was complete enough to use.", segmentId: "i2-s2" },
      { id: "e5", interviewId: "i4", participantCode: "P04", participantRole: "Agency founder", quote: "The checklist was useful because I could see progress.", context: "P04 valued visible progress but felt advanced setup tasks appeared too early.", segmentId: "i4-s2" }
    ]},
    { id: "t3", title: "Advanced setup arrives before first value", summary: "Tax, team permissions, and payment configuration interrupt the shortest path to a first invoice. Participants prefer to defer decisions that do not affect an initial test.", strength: "recurring", participantCount: 3, status: "draft", tags: ["Pain point", "Opportunity"], x: 230, y: 430, evidence: [
      { id: "e6", interviewId: "i1", participantCode: "P01", participantRole: "Studio owner", quote: "I don't want to configure everything before I know what good looks like.", context: "Tax and payment settings appeared before P01 could create an initial invoice.", segmentId: "i1-s4" },
      { id: "e7", interviewId: "i4", participantCode: "P04", participantRole: "Agency founder", quote: "Let me finish one invoice first. Team setup matters, just not before I've proved the basic workflow to myself.", context: "P04 postponed inviting teammates because permissions were introduced without enough context.", segmentId: "i4-s4" }
    ]},
    { id: "t4", title: "A safe test builds momentum", summary: "Participants invent workarounds to test the experience without contacting a real client. A guided test invoice could create an early success and reduce anxiety.", strength: "recurring", participantCount: 2, status: "draft", tags: ["Opportunity"], x: 650, y: 70, evidence: [
      { id: "e8", interviewId: "i2", participantCode: "P02", participantRole: "Consultant", quote: "I sent myself a test invoice. That gave me confidence, but I had to invent that step.", context: "P02 created a manual test because the product did not suggest a safe validation step.", segmentId: "i2-s4" },
      { id: "e9", interviewId: "i5", participantCode: "P05", participantRole: "Bookkeeper", quote: "A built-in test mode would have been much cleaner.", context: "P05 used a personal email address to simulate a customer.", segmentId: "i5-s4" }
    ]}
  ]
};
